spring:
  main:
    banner-mode: off

kafka-config:
  source-some-record-topic-name: some-record-topic
  source-some-record-group-name: some-record-group
  sink-process-some-record-command-topic-name: process-some-record-command-topic

  security:
    protocol: SASL_SSL
    sasl-mechanism: AWS_MSK_IAM
    sasl-jaas-config: software.amazon.msk.auth.iam.IAMLoginModule required;
    sasl-client-callback-handler-class: software.amazon.msk.auth.iam.IAMClientCallbackHandler

flink-config:
  checkpoint-interval: 30000
  min-pause-between-checkpoints: 3000
  checkpoint-timeout: 60000
  parallelism: 12
  max-parallelism: 20
  disable-generic-types: false
  list-state-ttl-value: 28

logging:
  level:
    root: info
    org.example: debug
    org.apache.flink: info
    org.apache.kafka: info
